services:
  backup-manager:
    build: .
    container_name: backup-manager
    ports:
      - "3000:3000"
    volumes:
      - data:/app/data
      - /backups/rclone.conf:/rclone/rclone.conf
      - /backups:/backups
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - admin_password=${ADMIN_PASSWORD}
    restart: unless-stopped

volumes:
  data:
