version: '3.8'

services:
  cron-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cron-job-scheduler
    ports:
      - "3000:3000"
    volumes:
      - data:/app/data
      - /backups/rclone.conf:/rclone/rclone.conf
      - /backups:/backups
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  data:
